apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 #Escala si el uso del cpu supera el 50%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 21 #Escala si el uso de la memoria supera el 23%
  - type: Resource
    resource:
      name: storage
      target:
        type: Utilization
        averageUtilization: 50